[substrate]
name = "sphereRadius_5.0"
position = "intra"

[simulation]
diffusivity = 1e-9
n_walkers = 100
n_t = 100

[waveform]
waveform_file = [
    "gradients/LTE0hz.csv",
    "gradients/LTE50hz.csv",
    "gradients/LTE100hz.csv",
    "gradients/STEiso.csv",
    "gradients/STEaniso.csv"
]
direction_file = "GFOD2_0100.txt"
num_b = 20
