[substrate]
name = "1_cylindersUP"
position = "intra"

[simulation]
diffusivity = 1e-9
n_walkers = 100
n_t = 100

[waveform]
waveform_file = [
    "gradients/test.csv"
]
direction_file = "GFOD2_0040.txt"
num_b = 6
