[substrate]
name = "spheres_3d_distribution_4_to_12_um"
position = "extra"
periodic = false

[simulation]
diffusivity = 1e-9
n_walkers = 100000
n_t = 10000

[waveform]
waveform_file = [
    "gradients/LTE0hz.csv",
    "gradients/LTE50hz.csv",
    "gradients/LTE100hz.csv",
    "gradients/STEiso.csv",
    "gradients/STEaniso.csv"
]
direction_file = "fibRot40.txt"
direction_file_fib = "fibRot40.txt"
num_b = 6
