[substrate]
name = "test"
position = "intra"

[simulation]
diffusivity = 1e-9
n_walkers = 1000
n_t = 1000

[waveform]
waveform_file = [
    "gradients/waveform1.csv",
    "gradients/waveform2.csv",
    "gradients/waveform3.csv",
    "gradients/waveform4.csv",
    "gradients/waveform5.csv"
]
num_directions = 30
num_b = 6
