[substrate]
name = "beaded_axon_fiber5_bead8_length_200_spacing50"
position = "intra"

[simulation]
diffusivity = 1e-9
n_walkers = 100000
n_t = 10000

[waveform]
waveform_file = [
    "gradients/LTE0hz.csv",
    "gradients/LTE50hz.csv",
    "gradients/LTE100hz.csv",
    "gradients/STEiso.csv",
    "gradients/STEaniso.csv"
]
num_directions = 30
num_b = 6
